In [4]:
from PIL import Image
import numpy as np
a = np.zeros((5, 5))
print(a)
im = Image.fromarray(a)
print(im)
im.convert('RGB')
print(im)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<PIL.Image.Image image mode=F size=5x5 at 0x7B2C1CCC1430>
<PIL.Image.Image image mode=F size=5x5 at 0x7B2C1CCC1430>


In [14]:
import torch
a = torch.tensor([1.1],requires_grad=True)
b = a * 2
b.add_(2)
a.add(2)
print(b)
print(a)
with torch.no_grad():
    b.mul_(2)
print(b)

tensor([4.2000], grad_fn=<AddBackward0>)
tensor([1.1000], requires_grad=True)
tensor([8.4000], grad_fn=<AddBackward0>)


In [2]:
import tqdm
for i in tqdm.tqdm(range(10)):
    print(i)

100%|██████████| 10/10 [00:00<00:00, 45343.83it/s]

0
1
2
3
4
5
6
7
8
9


In [1]:
a = 100
print("%06d" % a)

000100
